# Generated by Django 3.0.7 on 2020-06-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=250, null=True)),
                ('timespan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
