# Generated by Django 3.0.7 on 2020-06-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mydata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
